### ISSUE TITLE
Dilated convolution implemented in Keras?

### ISSUE THREAD

**Issue by caropj** [fchollet/keras#2978] opened 2016-06-14 13:36 UTC
Is there any way in Keras to performs a 2D convolution with dilated filters?
Fisher Yu, Vladlen Koltun (2016), Multi-Scale Context Aggregation by Dilated Convolutions. ICLR 2016

It is implemented in Lasagne/Torch, but I was wondering if it was available in Keras or planned to be.
https://github.com/fyu/dilation

Thanks and hope this is the right place to post such a question.

**Comment by fchollet** [comment] 2016-06-14 19:18
Haven't had time to look into it. Feel free to add the op to both backends and add a Keras layer for it.

**Comment by tboquet** [comment] 2016-06-14 20:26
Could it be worth it to wait for #4587 to be merged?

**Comment by caropj** [comment] 2016-06-15 07:46
Sure, let's wait. Thanks for the pointer, did not know Theano devs were on it.

**Comment by ouceduxzk** [comment] 2016-06-19 10:02
I am adapting the lasagne version into the keras , which uses 
  conv_out = T.nnet.abstract_conv.AbstractConv2d_gradWeights(
                imshp=image_shape, kshp=filter_shape,
                subsample= rate , border_mode=border_mode,
                filter_flip=False
            )
The problem is that its convenient to have imshp and kshp in lasange by self.input_shape, self.output_shape, however, in keras, each layer does not have a 'incoming' layer as a parameter,  how should I specify the these two parameters to make it work?

The code is currently here : https://github.com/ouceduxzk/dilatedConv2d

**Comment by nouiz** [comment] 2016-06-20 13:31
Can you use the symbolic shape of the inputs? a_theano_var.shape for
example.

**Comment by ouceduxzk** [comment] 2016-06-25 16:22
Can you give me a hint on how to do that ？I am not an expert of theano. 

Thanks

**Comment by fchollet** [comment] 2016-06-30 19:37
What happens if you try to use `T.nnet.abstract_conv.AbstractConv2d_gradWeights` without the image shape available? Is that possible?

Most of the time it is possible to have the image shape available in Keras, but not always (e.g. if you two data flows with different shapes going through the same layer, then the input shape of that layer is ill-defined).

**Comment by jskDr** [comment] 2016-06-30 19:44
Thank you for your kindness answer. I love Keres which seems to be sklearn
2.0.

On Thu, Jun 30, 2016 at 3:38 PM François Chollet <notifications@github.com>
wrote:

> What happens if you try to use
> T.nnet.abstract_conv.AbstractConv2d_gradWeights without the image shape
> available? Is that possible?
>
> Most of the time it is possible to have the image shape available in
> Keras, but not always (e.g. if you two data flows with different shapes
> going through the same layer, then the input shape of that layer is
> ill-defined).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fchollet/keras/issues/2978#issuecomment-229765863>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACchnbXqg1VoQMS5-jMTfhxZPKPIk1Kyks5qRBsegaJpZM4I1U_7>
> .
>
-- 

Sungjin (James) Kim, PhD

Postdoc, CCB in Harvard

sungjinkim@fas.harvard.edu

[Web] http://aspuru.chem.harvard.edu/james-sungjin-kim/

[Linkedin] https://www.linkedin.com/in/jamessungjinkim

[Facebook] https://www.facebook.com/jamessungjin.kim

[alternative email] jamessungjin.kim@gmail.com

**Comment by fchollet** [comment] 2016-06-30 19:53
@nouiz does this sound like a reasonable way to implement this dilated convolution business in Theano?

```python
        op = T.nnet.abstract_conv.AbstractConv2d_gradWeights(
            imshp=image_shape,
            kshp=filter_shape,
            subsample=(atrous_rate, atrous_rate),
            border_mode=th_border_mode,
            filter_flip=False)
        conv_out = op(x.transpose(1, 0, 2, 3), kernel)
        conv_out = conv_out.transpose(1, 0, 2, 3)
```

Note: `image_shape` not be None.

**Comment by caropj** [comment] 2016-07-01 11:24
Seems like Theano's implementation of 2D dilated convolution has been merged 
[https://github.com/Theano/Theano/pull/4587](https://github.com/Theano/Theano/pull/4587)

**Comment by fchollet** [comment] 2016-07-01 18:36
Cool, it looks like it will make things simpler.

TensorFlow also has an implementation of it: https://github.com/tensorflow/tensorflow/commit/c1aa6423e35803d08b7092a874632b6b7b13a130

**Comment by nouiz** [comment] 2016-07-06 17:56
I didn't spot problem with your code for dilated convolution. But I don't
completly understand it.

I don't know which version will be faster (using the code snippet above or
the Theano version that is based on the original caffe version). If someone
have time, timing both version would be useful. The caffe version support
more feature then the code snippet, but the code snippet could be faster as
it allow to use cudnn.

**Comment by fchollet** [comment] 2016-07-15 04:21
Added yesterday as `AtrousConv2D`.

**Closed by fchollet** 2016-07-15 04:21 UTC

**Comment by TurnaevEvgeny** [comment] 2016-07-27 06:35
Hi,
   I am getting:
```
/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py:917: UserWarning: ['filter_dilation'] are now deprecated in `tensor.nnet.abstract_conv.conv2d` interface and will be ignored.
  filter_dilation=filter_dilation)
```
when using AtrousConv2D

```
In [4]: theano.__version__
Out[4]: '0.8.2'
```
Should I update Theano? Is it safe to ignore deprecation warning for me?

**Comment by DrSleep** [comment] 2016-08-02 06:46
@TurnaevEvgeny, had the same warning. Solved by the update to 0.9.0.
Guess, that with the warning showing off, the dilation is not used at all.

**Comment by dk683** [comment] 2016-10-12 15:09
Hello! Would there be a support for 3D in the future release, i.e., `AtrousConvolution3D`?

**Comment by yliu7366** [comment] 2018-03-13 02:56
Unable to find the AtrousConv2D documentation on the Keras docmentation (https://keras.io/), is it removed or renamed? Thanks,

**Comment by faltinl** [comment] 2019-01-12 09:13
It's a verly late reply, I know, but might nevertheless be useful for latecomers like myself: In Keras version 2.2.0.9000 index a dilation option is offered for both standard nD convolution layers as well as for separable conv layers.
