### ISSUE TITLE
IMDB dataset oov flipped bit.

### ISSUE THREAD

**Issue by tshauck** [fchollet/keras#3688] opened 2016-09-04 20:29 UTC
Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

It looks like if you pass `oov_char=None` into `imdb.load_data` the new dataset is created with only words above `nb_words` or below `skip_top`.  I may be misunderstanding, but it seems like it should be the negation of that.

Here's a quick example:

```
from keras.datasets import imdb
import numpy as np

(X_train, y_train), (X_test, y_test) =  imdb.load_data(oov_char=None, nb_words=200)
print(np.min([np.min(x) for x in X_train]))
#200
print(np.max([np.max(x) for x in X_train]))
#88587
```

I would expect that the dataset would only retain values less than 200.

For the potentially offending code, starting on line 83 of keras/imdb.py...

```
    if oov_char is not None:
        X = [[oov_char if (w >= nb_words or w < skip_top) else w for w in x] for x in X]
    else:
        nX = []
        for x in X:
            nx = []
            for w in x:
                if (w >= nb_words or w < skip_top):
                    nx.append(w)
            nX.append(nx)
        X = nX
```

In particular `if (w >= nb_words or w < skip_top)`.  If this is in fact an issue, happy to submit a PR.

**Comment by 1064950364** [comment] 2017-02-08 06:16
I'm just as confused as you are，I think it should be ' if not (w >= nb_words or w < skip_top)'.
what you said occurs if and only if 'oov_char=None'.

**Comment by dhilton** [comment] 2017-04-11 20:15
This seems to be also the same in the reuters dataset load function:

```
from keras.datasets import imdb, reuters
import numpy as np


print("Test IMDB dataset")
(X_train, y_train), (X_test, y_test) =  imdb.load_data(oov_char=None, num_words=200)
print(np.min([np.min(x) for x in X_train]))
#200
print(np.max([np.max(x) for x in X_train]))
#88587


print("Second round: oov_char set to 9")
(X_train, y_train), (X_test, y_test) =  imdb.load_data(oov_char=9, num_words=200)
print(np.min([np.min(x) for x in X_train]))
#1
print(np.max([np.max(x) for x in X_train]))
#199

print("Test reuters dataset")
(X_train, y_train), (X_test, y_test) =  reuters.load_data(oov_char=None, num_words=200)
print(np.min([np.min(x) for x in X_train]))
#200
print(np.max([np.max(x) for x in X_train]))
#30982

print("Second round reuters: oov_char set to 9")
(X_train, y_train), (X_test, y_test) =  reuters.load_data(oov_char=9, num_words=200)
print(np.min([np.min(x) for x in X_train]))
#1
print(np.max([np.max(x) for x in X_train]))
#199

```
If you explicitly set `oov_char=2` it gives you the expected 1 and 199 results for the test. My suggested fix is: (NOTE: change of variable names since bug reported)
```
if oov_char is None:
     # The default specified in the function signature.
     oov_char = 2
xs = [[oov_char if (w >= num_words or w < skip_top) else w for w in x] for x in xs]

```

This needs to be patched to both the reuters.py and the imdb.py files. If this works for maintainers happy to work into a PR. This would also allow the closure of #6114 PR.

**Comment by fchollet** [comment] 2017-04-11 20:59
A fix is welcome. Keep in mind that:

- the same indices should still map to the same words as before
- we should not return indices higher than what we returned before

This is for backwards compatibility. The fix should respect these
constraints.

**Comment by ghego** [comment] 2017-04-25 04:40
Also it seems to me that:

```python
    if not num_words:
        num_words = max([max(x) for x in xs])
```
combined with:

```python
if (w >= nb_words or w < skip_top)
```

seems will always eliminate the word with the highest value, so should we change the calculation of `num_words` to:

```python
    if not num_words:
        num_words = max([max(x) for x in xs]) + 1
```
?

**Comment by ghego** [comment] 2017-04-25 05:05
And finally the docstring is confusing:
https://github.com/fchollet/keras/blob/master/keras/datasets/imdb.py#L21
says:
`maxlen: truncate sequences after this length.`

but maxlen actually purges sequences longer than that length:
https://github.com/fchollet/keras/blob/master/keras/datasets/imdb.py#L77

which one is the intended behavior?

**Comment by ghego** [comment] 2017-04-25 05:13
and `skip_top` overrides `start_char` and replaces it with `oov_char`, which seems very confusing to me:

https://github.com/fchollet/keras/blob/master/keras/datasets/imdb.py#L97

**Comment by pavlin99th** [comment] 2017-04-25 09:37
@ghego, you are right! I've addressed these issues in #6114 PR. But there are backwards compatibility concerns with previously trained models.

**Comment by ghego** [comment] 2017-04-25 16:37
@pavlin99th can you verify that those concerns are addressed?

**Comment by pavlin99th** [comment] 2017-04-25 18:59
PR #6397 deals with flipped `oov_char` condition only and should close this issue.
Let's discuss `start_char` and `skip_top` in #6114. I don't have a clear understanding how further changes can affect saved models.

**Closed** 2017-04-26 02:48 UTC
