### ISSUE TITLE
TypeError: transfer_type{0} on mnist_mlp.py

### ISSUE THREAD

**Issue by evanfeinberg** [fchollet/keras#728] opened 2015-09-26 00:02 UTC
Hi, 

I just installed keras from master on Github and seem to be encountering some errors with the example files. I'm running on CentOS 6.6 on a GPU node. A Theano test script worked without a hitch. However, when running mnist_mlp.py, for example, I am thrown the following error:

```
[enf@gpu-9-3 ~/keras/examples]$ python mnist_mlp.py 
Using gpu device 0: GeForce GTX TITAN Black (CNMeM is disabled)
60000 train samples
10000 test samples
ERROR (theano.gof.opt): SeqOptimizer apply inplace_elemwise_optimizer
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/enf/Theano/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/enf/Theano/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/enf/Theano/theano/tensor/opt.py", line 404, in inplace_elemwise_optimizer
    for i in xrange(len(node.outputs))]))
  File "/home/enf/Theano/theano/scalar/basic.py", line 1998, in __init__
    raise TypeError(o_type)
TypeError: transfer_type{0}
```

The same error was thrown from the other example scripts as well. 

Any idea what this means or how to fix it? 

Thank you for your help!!

Cheers,
Evan

**Comment by mmmikael** [comment] 2015-09-28 12:16
I am getting this too with the bleeding-edge version of Theano.

**Comment by evanfeinberg** [comment] 2015-09-28 20:38
Thanks for your response, @mmmikael  -- do you not see this error in an earlier version, and, if so, is that version compatible with GPU's?

**Comment by tboquet** [comment] 2015-09-29 03:34
Hi, I'm getting the same warning/error but all the test are passing using nosetests. I updated to the latest version of Theano and Keras. I tried to fit the same model with both the latest version and the python 3 version of Theano and I have the same results, You should maybe ask the question to Theano developers :).

**Comment by fchollet** [comment] 2015-09-29 05:21
Most likely a Theano issue. I would recommend raising this with the Theano devs... in the meantime, I guess you could use a slightly older Theano version.

**Comment by mmmikael** [comment] 2015-09-29 12:22
@evanfeinberg GeForce GTX TITAN X
I opened a Theano issue [here](https://github.com/Theano/Theano/issues/3463).

**Comment by evanfeinberg** [comment] 2015-09-30 06:54
I reverted to an earlier version of Theano and it seems to have resolved the issue with running mnist_mlp.py. Thank you for the input, everyone!

**Comment by nouiz** [comment] 2015-09-30 15:07
We merged a fix for this in Theano. As I'm not able to reproduce it, could you update Theano and confirm that it is fixed?

**Comment by colincsl** [comment] 2015-10-01 17:52
I was having this same problem. I just updated Theano and it did indeed fix the issue.

**Comment by fchollet** [comment] 2015-10-01 21:55
Awesome! Props to the Theano devs.

**Closed by fchollet** 2015-10-01 21:55 UTC
